apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.app }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.port }}
  selector:
    app: {{ .Values.prometheus.app }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.grafana.app }}
  name: {{ .Values.grafana.app }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.grafana.port }}
  selector:
    app: {{ .Values.grafana.app }}
